### ISSUE TITLE
error message "free(): double free detected in tcache 2"

### ISSUE THREAD

**Issue by Elizaluckianchikova** [yangao07/TideHunter#13]
I am reaching out to you regarding an issue encountered while using the tool on short reads. When downloading the Linux build available on your GitHub repository, a memory overload issue occurs with the error message:
 **"free(): double free detected in tcache 2".** 
I have to trim the reads and The result becomes less  accurate.
Below I attach the output file and the command I used.
"TideHunter /mnt/data/temp/000000000500.MGI.cutadapt_000000_errored.fq --min-len 40 --thread 8  --out-fmt 4  > /mnt/data/temp/tide"
[output.txt](https://github.com/user-attachments/files/15741098/output.txt)
How can it be solved?

**Comment by yangao07** [comment]
Sure, can you share your input data? I can take a look.

**Comment by Elizaluckianchikova** [comment]
Yes, I send.

пт, 7 июн. 2024 г. в 18:05, Yan Gao ***@***.***>:

**Comment by Elizaluckianchikova** [comment]
Sorry , I have attached and sent my output file here, in the penultimate letter. Sincerely, Luckyanchikova E.10 июня 2024 г., в 14:26, Yan Gao ***@***.***> написал(а):﻿
Sorry, but send to where?

**Comment by yangao07** [comment]
I saw your output.txt attached. 
I need the input file to do some debugging. Can you share it?

**Comment by Elizaluckianchikova** [comment]
The latest Linux version contained on GitHub. Sincerely, Luckyanchikova E.10 июня 2024 г., в 14:38, Yan Gao ***@***.***> написал(а):﻿
And also, what is the version you are using?

**Comment by yangao07** [comment]
OK, your input data?

**Comment by Elizaluckianchikova** [comment]
YesSincerely, Luckyanchikova E.11 июня 2024 г., в 00:56, Yan Gao ***@***.***> написал(а):﻿
OK, your input data?

**Comment by Elizaluckianchikova** [comment]
Sorry, I miss understood.

вт, 11 июн. 2024 г. в 10:55, Елизавета Лукьянчикова <
***@***.***>:

**Comment by yangao07** [comment]
I am sorry, but the file you upload is very small, only these two reads
```
@E100079243L1C004R03004248215/2
AATGGAATCGTCATAGAATGGAATCGAATG
+
CCCCDCCCCD;DCBC+B8CB7CBCDCCCCC
@E100079243L1C005R04004405543/2
ATTNGATTGCA
+
``` 
I will not reply until you are able to provide any more information.

**Comment by pustoshilov-d** [comment]
@yangao07, good day!
I apologize for my student's @Elizaluckianchikova communication
About the small file: we assumed that it is not good to upload a large amount of genomic data to the internet. So we detected problematic reads and send it.

Here is part of the fastq (78mb unpacked):
[000000000500.MGI.cutadapt_000000.fq.gz](https://github.com/user-attachments/files/15823279/000000000500.MGI.cutadapt_000000.fq.gz)

MGI short-read sequencer
Trimming cutadapt
TideHunter-v1.5.4 under Docker
CPU 40 RAM 400, limit is not reached at startup

Run with the command 
`TideHunter  --min-len 40 --thread 20 --out-fmt 4 000000000500.MGI.cutadapt_000000.fq.gz > tide.output`

Error:
```
free(): double free detected in tcache 2
Aborted (core dumped)
```

Results:
[tide.output.gz](https://github.com/user-attachments/files/15823295/tide.output.gz)

Potentially problematic reads:
```
@E100079243L1C004R03004248215/2
AATGGAATCGTCATAGAATGGAATCGAATG
+
CCCCDCCCCD;DCBC+B8CB7CBCDCCCCC
@E100079243L1C005R04004405543/2
ATTNGATTGCA
+
CDC!DCDCDCB
```
We though the problem is in N-base, but there is a lot of it in other reads.

Is there enough information here?
We will be grateful if you can help us to understand the cause of the error.

**Comment by yangao07** [comment]
Hi, I can reproduce the error msg with the data you provided.
This bug was fixed in v1.5.5, which was not pushed to conda previously.
Right now, you can build the TideHunter program from source to get the v1.5.5.
Or you can wait a few days, the conda will update to the latest version.

**Comment by yangao07** [comment]
The conda has been updated to v1.5.5, I will close this thread, feel free to re-open it if you see any errors again.

**Comment by Elizaluckianchikova** [comment]
We are truly grateful for your work; it has been immensely helpful.
